<?php

namespace Database\Seeders;

use App\Models\Pais;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class PaisSeeder extends Seeder
{
    /**
     * Lista oficial de paises del DANE (Estandar M49 / ALADI, diciembre 2023).
     * codigo = Codigo ALADI (3 digitos, Colombia = 169); nombre = Descripcion pais.
     */
    public function run(): void
    {
        $paises = [
            ['013', 'Afganistán'],
            ['017', 'Albania'],
            ['023', 'Alemania'],
            ['037', 'Andorra'],
            ['040', 'Angola'],
            ['041', 'Anguila'],
            ['043', 'Antigua y Barbuda'],
            ['024', 'Antártida'],
            ['053', 'Arabia Saudita'],
            ['059', 'Argelia'],
            ['063', 'Argentina'],
            ['026', 'Armenia'],
            ['027', 'Aruba'],
            ['069', 'Australia'],
            ['072', 'Austria'],
            ['074', 'Azerbaiyán'],
            ['077', 'Bahamas'],
            ['080', 'Bahrein'],
            ['081', 'Bangladesh'],
            ['083', 'Barbados'],
            ['091', 'Belarús'],
            ['088', 'Belice'],
            ['229', 'Benin'],
            ['090', 'Bermudas'],
            ['119', 'Bhután'],
            ['097', 'Bolivia (Estado Plurinacional de)'],
            ['098', 'Bonaire, San Eustaquio y Saba'],
            ['029', 'Bosnia y Herzegovina'],
            ['101', 'Botswana'],
            ['105', 'Brasil'],
            ['108', 'Brunei Darussalam'],
            ['111', 'Bulgaria'],
            ['031', 'Burkina Faso'],
            ['115', 'Burundi'],
            ['087', 'Bélgica'],
            ['127', 'Cabo Verde'],
            ['141', 'Camboya'],
            ['145', 'Camerún'],
            ['149', 'Canadá'],
            ['203', 'Chad'],
            ['644', 'Chequia'],
            ['211', 'Chile'],
            ['215', 'China'],
            ['221', 'Chipre'],
            ['169', 'Colombia'],
            ['173', 'Comoras'],
            ['177', 'Congo'],
            ['196', 'Costa Rica'],
            ['198', 'Croacia'],
            ['199', 'Cuba'],
            ['200', 'Curazao'],
            ['193', 'Côte d’Ivoire'],
            ['232', 'Dinamarca'],
            ['783', 'Djibouti'],
            ['235', 'Dominica'],
            ['239', 'Ecuador'],
            ['240', 'Egipto'],
            ['242', 'El Salvador'],
            ['244', 'Emiratos Árabes Unidos'],
            ['243', 'Eritrea'],
            ['246', 'Eslovaquia'],
            ['247', 'Eslovenia'],
            ['245', 'España'],
            ['579', 'Estado de Palestina'],
            ['249', 'Estados Unidos de América'],
            ['251', 'Estonia'],
            ['773', 'Eswatini'],
            ['253', 'Etiopía'],
            ['676', 'Federación de Rusia'],
            ['870', 'Fiji'],
            ['267', 'Filipinas'],
            ['271', 'Finlandia'],
            ['275', 'Francia'],
            ['281', 'Gabón'],
            ['285', 'Gambia'],
            ['287', 'Georgia'],
            ['694', 'Georgia del Sur y las Islas Sandwich del Sur'],
            ['289', 'Ghana'],
            ['293', 'Gibraltar'],
            ['297', 'Granada'],
            ['301', 'Grecia'],
            ['305', 'Groenlandia'],
            ['309', 'Guadalupe'],
            ['313', 'Guam'],
            ['317', 'Guatemala'],
            ['325', 'Guayana Francesa'],
            ['327', 'Guernsey'],
            ['329', 'Guinea'],
            ['331', 'Guinea Ecuatorial'],
            ['334', 'Guinea-Bissau'],
            ['337', 'Guyana'],
            ['341', 'Haití'],
            ['345', 'Honduras'],
            ['351', 'Hong Kong'],
            ['355', 'Hungría'],
            ['361', 'India'],
            ['365', 'Indonesia'],
            ['369', 'Iraq'],
            ['375', 'Irlanda'],
            ['372', 'Irán (República Islámica del)'],
            ['102', 'Isla Bouvet'],
            ['468', 'Isla de Man'],
            ['511', 'Isla de Navidad'],
            ['535', 'Isla Norfolk'],
            ['379', 'Islandia'],
            ['137', 'Islas Caimán'],
            ['165', 'Islas Cocos (Keeling)'],
            ['183', 'Islas Cook'],
            ['259', 'Islas Feroe'],
            ['343', 'Islas Heard y McDonald'],
            ['470', 'Islas Malvinas'],
            ['469', 'Islas Marianas del Norte'],
            ['472', 'Islas Marshall'],
            ['566', 'Islas menores alejadas de los Estados Unidos'],
            ['677', 'Islas Salomón'],
            ['772', 'Islas Svalbard y Jan Mayen'],
            ['823', 'Islas Turcas y Caicos'],
            ['863', 'Islas Vírgenes Británicas'],
            ['866', 'Islas Vírgenes de los Estados Unidos'],
            ['875', 'Islas Wallis y Futuna'],
            ['015', 'Islas Åland'],
            ['383', 'Israel'],
            ['386', 'Italia'],
            ['391', 'Jamaica'],
            ['399', 'Japón'],
            ['401', 'Jersey'],
            ['403', 'Jordania'],
            ['406', 'Kazajstán'],
            ['410', 'Kenya'],
            ['412', 'Kirguistán'],
            ['411', 'Kiribati'],
            ['413', 'Kuwait'],
            ['426', 'Lesotho'],
            ['429', 'Letonia'],
            ['434', 'Liberia'],
            ['438', 'Libia'],
            ['440', 'Liechtenstein'],
            ['443', 'Lituania'],
            ['445', 'Luxemburgo'],
            ['431', 'Líbano'],
            ['447', 'Macao'],
            ['448', 'Macedonia del Norte'],
            ['450', 'Madagascar'],
            ['455', 'Malasia'],
            ['458', 'Malawi'],
            ['461', 'Maldivas'],
            ['467', 'Malta'],
            ['464', 'Malí'],
            ['474', 'Marruecos'],
            ['477', 'Martinica'],
            ['485', 'Mauricio'],
            ['488', 'Mauritania'],
            ['489', 'Mayotte'],
            ['494', 'Micronesia (Estados Federados de)'],
            ['497', 'Mongolia'],
            ['500', 'Montenegro'],
            ['501', 'Montserrat'],
            ['505', 'Mozambique'],
            ['093', 'Myanmar'],
            ['493', 'México'],
            ['498', 'Mónaco'],
            ['507', 'Namibia'],
            ['508', 'Nauru'],
            ['517', 'Nepal'],
            ['521', 'Nicaragua'],
            ['528', 'Nigeria'],
            ['531', 'Niue'],
            ['999', 'No declarados'],
            ['538', 'Noruega'],
            ['542', 'Nueva Caledonia'],
            ['548', 'Nueva Zelandia'],
            ['525', 'Níger'],
            ['556', 'Omán'],
            ['576', 'Pakistán'],
            ['578', 'Palau'],
            ['580', 'Panamá'],
            ['545', 'Papua Nueva Guinea'],
            ['586', 'Paraguay'],
            ['573', 'Países Bajos'],
            ['589', 'Perú'],
            ['593', 'Pitcairn'],
            ['599', 'Polinesia Francesa'],
            ['603', 'Polonia'],
            ['607', 'Portugal'],
            ['611', 'Puerto Rico'],
            ['618', 'Qatar'],
            ['628', 'Reino Unido de Gran Bretaña e Irlanda del Norte'],
            ['640', 'República Centroafricana'],
            ['190', 'República de Corea'],
            ['496', 'República de Moldova'],
            ['888', 'República Democrática del Congo'],
            ['420', 'República Democrática Popular Lao'],
            ['647', 'República Dominicana'],
            ['187', 'República Popular Democrática de Corea'],
            ['780', 'República Unida de Tanzanía'],
            ['744', 'República Árabe Siria'],
            ['660', 'Reunión'],
            ['670', 'Rumania'],
            ['675', 'Rwanda'],
            ['695', 'Saint Kitts y Nevis'],
            ['687', 'Samoa'],
            ['690', 'Samoa Americana'],
            ['693', 'San Bartolomé'],
            ['697', 'San Marino'],
            ['698', 'San Martín (parte francesa)'],
            ['699', 'San Martín (parte Holandesa)'],
            ['700', 'San Pedro y Miquelón'],
            ['705', 'San Vicente y las Granadinas'],
            ['710', 'Santa Elena, Ascensión y Tristán de Acuña'],
            ['715', 'Santa Lucía'],
            ['159', 'Santa Sede'],
            ['720', 'Santo Tomé y Príncipe'],
            ['728', 'Senegal'],
            ['729', 'Serbia'],
            ['731', 'Seychelles'],
            ['735', 'Sierra Leona'],
            ['741', 'Singapur'],
            ['748', 'Somalia'],
            ['750', 'Sri Lanka'],
            ['756', 'Sudáfrica'],
            ['759', 'Sudán'],
            ['760', 'Sudán del Sur'],
            ['764', 'Suecia'],
            ['767', 'Suiza'],
            ['770', 'Suriname'],
            ['685', 'Sáhara Occidental'],
            ['776', 'Tailandia'],
            ['218', 'Taiwán'],
            ['774', 'Tayikistán'],
            ['787', 'Territorio Británico del Océano Índico'],
            ['786', 'Territorio de las Tierras Australes Francesas'],
            ['788', 'Timor-Leste'],
            ['800', 'Togo'],
            ['805', 'Tokelau'],
            ['810', 'Tonga'],
            ['815', 'Trinidad y Tabago'],
            ['825', 'Turkmenistán'],
            ['827', 'Turquía'],
            ['828', 'Tuvalu'],
            ['820', 'Túnez'],
            ['830', 'Ucrania'],
            ['833', 'Uganda'],
            ['845', 'Uruguay'],
            ['847', 'Uzbekistán'],
            ['551', 'Vanuatu'],
            ['850', 'Venezuela (República Bolivariana de)'],
            ['855', 'Viet Nam'],
            ['880', 'Yemen'],
            ['890', 'Zambia'],
            ['665', 'Zimbabwe'],
            ['900', 'Zona franca de Argentina  (Genérico)'],
            ['908', 'Zona franca de Bolivia (Genérico)'],
            ['915', 'Zona franca de Brasil (Genérico)'],
            ['923', 'Zona franca de Chile (Genérico)'],
            ['931', 'Zona franca de Colombia (Genérico)'],
            ['938', 'Zona franca de Cuba (Genérico)'],
            ['946', 'Zona franca de Ecuador (Genérico)'],
            ['954', 'Zona franca de México (Genérico)'],
            ['962', 'Zona franca de Panamá (Genérico)'],
            ['969', 'Zona franca de Paraguay (Genérico)'],
            ['977', 'Zona franca de Perú (Genérico)'],
            ['985', 'Zona franca de Uruguay (Genérico)'],
            ['990', 'Zona franca de Venezuela (Genérico)'],
        ];

        DB::table('paises')->delete();
        foreach ($paises as [$codigo, $nombre]) {
            Pais::create(['codigo' => $codigo, 'nombre' => $nombre]);
        }
    }
}
